/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attempt {
  'duration' : bigint,
  'score' : bigint,
  'timestamp' : Time,
}
export interface ExamConfig {
  'timeLimitMinutes' : bigint,
  'passingScorePercent' : bigint,
}
export interface QuestionDTO {
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export interface SubmitAttemptInput {
  'duration' : bigint,
  'responses' : Array<bigint>,
}
export interface SubmitAttemptResult {
  'score' : bigint,
  'timestamp' : Time,
  'passed' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'addQuestion' : ActorMethod<[QuestionDTO], undefined>,
  'getExamConfig' : ActorMethod<[], ExamConfig>,
  'getQuestions' : ActorMethod<[], Array<QuestionDTO>>,
  'getUserAttempts' : ActorMethod<[Principal], Array<Attempt>>,
  'setExamConfig' : ActorMethod<[ExamConfig], undefined>,
  'submitAttempt' : ActorMethod<[SubmitAttemptInput], SubmitAttemptResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];