/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionDTO = IDL.Record({
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const ExamConfig = IDL.Record({
  'timeLimitMinutes' : IDL.Nat,
  'passingScorePercent' : IDL.Nat,
});
export const Time = IDL.Int;
export const Attempt = IDL.Record({
  'duration' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : Time,
});
export const SubmitAttemptInput = IDL.Record({
  'duration' : IDL.Nat,
  'responses' : IDL.Vec(IDL.Nat),
});
export const SubmitAttemptResult = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : Time,
  'passed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func([QuestionDTO], [], []),
  'getExamConfig' : IDL.Func([], [ExamConfig], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(QuestionDTO)], ['query']),
  'getUserAttempts' : IDL.Func([IDL.Principal], [IDL.Vec(Attempt)], ['query']),
  'setExamConfig' : IDL.Func([ExamConfig], [], []),
  'submitAttempt' : IDL.Func([SubmitAttemptInput], [SubmitAttemptResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionDTO = IDL.Record({
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const ExamConfig = IDL.Record({
    'timeLimitMinutes' : IDL.Nat,
    'passingScorePercent' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Attempt = IDL.Record({
    'duration' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  const SubmitAttemptInput = IDL.Record({
    'duration' : IDL.Nat,
    'responses' : IDL.Vec(IDL.Nat),
  });
  const SubmitAttemptResult = IDL.Record({
    'score' : IDL.Nat,
    'timestamp' : Time,
    'passed' : IDL.Bool,
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func([QuestionDTO], [], []),
    'getExamConfig' : IDL.Func([], [ExamConfig], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(QuestionDTO)], ['query']),
    'getUserAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Attempt)],
        ['query'],
      ),
    'setExamConfig' : IDL.Func([ExamConfig], [], []),
    'submitAttempt' : IDL.Func([SubmitAttemptInput], [SubmitAttemptResult], []),
  });
};

export const init = ({ IDL }) => { return []; };